[build]
  command = "pip install -r requirements.txt && python manage.py collectstatic --noinput"
  publish = "staticfiles"

[build.environment]
  PYTHON_VERSION = "3.9"

[context.production]
  environment = { DJANGO_SETTINGS_MODULE = "primehive.settings_prod" }

[context.deploy-preview]
  environment = { DJANGO_SETTINGS_MODULE = "primehive.settings_prod" }

[context.branch-deploy]
  environment = { DJANGO_SETTINGS_MODULE = "primehive.settings" }

# Redirects for Django application
[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/media/*"
  to = "/media/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/django"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
